### PR TITLE
Update JSDocs to allow correct type checks

### PR DESCRIPTION
**Pull request by dcbrwn**
An attempt to address #323. This PR renames all data types to Pascal case and adds @typedefs describing them. It's the cheapest solution I came up with that requires minimum maintenance.

Also I intentionally renamed types in docs. Is this okay?

Typechecks now working a bit better relying solely on JSDocs:
```typescript
import { vec2, vec3 } from './src/index';

let a: vec2.Vec2;

a = vec3.create();

/* tsc outputs

Type 'Float32Array | [number, number, number]' is not assignable to type '[number, number] | Float32Array'.
  Type '[number, number, number]' is not assignable to type '[number, number] | Float32Array'.
    Type '[number, number, number]' is not assignable to type '[number, number]'.
      Types of property 'length' are incompatible.
        Type '3' is not assignable to type '2'.

*/
```

### CODE REVIEW

**Comment by dcbrwn** [comment]
Caveat: tuple syntax requires at least typescript 3.

**Comment by stefnotch** [comment]
This seems to be a pretty decent solution. (I took a look at it and couldn't figure out anything better, or anything that would allow us to use `vec2` as a type **and** a module instead of having to type `vec2.Vec2`)

**Comment by stefnotch** [comment]
I found a way to get type checking to work with TypeScript that requires basically no maintenance. 😄 

```typescript
// b.ts
import * as mat3i from "./mat3.js";
//import { mat3 } from "./mat3.js";

let mat3: typeof mat3i = mat3i;
type mat3 = number[];

export { mat3 };
```

**Comment by stefnotch** [comment]
Did you manage to build the documentation with this?

**Comment by stefnotch** [comment]
I'm currently working on a better solution. It's possible that the best solution would be to make the switch to TypeScript.

**Pull request closed without merging**
