### PR TITLE
Update vec3.angle to match vec2.angle update

### PR DESCRIPTION
**Pull request by arccoza**
I updated vec3.angle to match my previous PR for vec2.angle.

### CODE REVIEW

**Comment by arccoza** [comment]
https://repl.it/@arccoza/glMatrix-vec3angle
https://jsperf.com/angle-between-two-vectors-3d/1

**Comment by stefnotch** [comment]
You can apparently get marginally faster results (Firefox 72) by first saving the numbers to local variables.
```javascript
  function angle3(a, b) {
    let a0 = a[0], a1 = a[1], a2 = a[2], b0 = b[0], b1 = b[1], b2 = b[2];
    let mag1 = Math.sqrt(a0*a0 + a1*a1 + a2*a2),
    mag2 = Math.sqrt(b0*b0 + b1*b1 + b2*b2),
    mag = mag1 * mag2,
    cosine = mag && (dot(a, b) / mag);
    return Math.acos(Math.min(Math.max(cosine, -1), 1));
  }
```

**Comment by arccoza** [comment]
Sure, fewer lookups, updated.

**Comment by stefnotch** [comment]
Thank you!

**Pull request merged**
