### PR TITLE
Deprecation Warnings

### PR DESCRIPTION
**Pull request by andrevenancio**
Fixing deprecation warning when using as npm module.

https://github.com/toji/gl-matrix/issues/267

### CODE REVIEW

**Comment by andrevenancio** [comment]
@toji If you approve this in the meantime, dont forget to do a `npm publish` so the new version goes to npmjs :)

**Comment by stefnotch** [comment]
@andrevenancio Are you willing to reopen the PR? I

**Comment by andrevenancio** [comment]
Hi @stefnotch!
I had lost all hopes in December that this project was being maintained so I closed this issue.

I'm happy you're picking this up. Will try to fix this tonight.

**Comment by andrevenancio** [comment]
Hey, so I've done a few things here

* all npm packages are updated to their latest version
* webpack was updated to latest version
* new docs generated
* new source files generated.

Now, this is a bit of a personal choice but I think adds value to it:

Every time we need a version bump, we just need to do it on the package.json before running `npm run build-all`. This will update the LICENSE.md file with the correct year range (2015-current year) and also update the `VERSION` file with the latest version. and update the copyright version on the `dist/` folder..

I personally think this is a good thing as you now just need to update in one place and avoids leaving behind a forgotten file with an old version/license.

Another thing I think benefits the project is organising all build processes (node + webpack) into their own folder. Just to keep things a bit more tidy.

And I think that's all :)

Let me know if you want any amends. Happy to help on any other issues too.

Thanks

**Comment by stefnotch** [comment]
@andrevenancio The travis build apparently still fails. Might have been caused by the `webpack` version bump.

**Comment by andrevenancio** [comment]
oops! let me check this again.

**Comment by stefnotch** [comment]
@andrevenancio Looks like the build is still failing.

**Comment by andrevenancio** [comment]
Ok, sorry took a while it was a bit of trial and error. Updated the node version and also fixed the travis script which wasn't pointing to the right config. everything should be ok now. Let me know your thoughts regarding the other points above.

**Comment by stefnotch** [comment]
@andrevenancio 
To start off: Thank you so much for all of this! 😄 

I think it's great! Though, I'm slightly worried about backwards compatibility.
Though, everybody who uses an older version of node can still use [dist/gl-matrix.js](https://github.com/toji/gl-matrix/blob/master/dist/gl-matrix.js), right?

**Comment by andrevenancio** [comment]
Yeah they should. to be honest I think I can revert it back because my suspicion is that my .travis file was the one causing the errors. let me revert that then

**Comment by andrevenancio** [comment]
Ok, so I think we have no problem by specifying the `node_js` version on travis as we just need to do that so travis can create an instance of node (through nvm) install our packages and handle the tests.

Right now with version 4.2 we have a warning generated by uglify `uglifyjs-webpack-plugin@1.2.5: wanted: {"node":">= 4.8 < 5.0.0 || >= 5.10"} (current: {"node":"4.2.6","npm":"2.14.12"})`.

We can either update it to 4.8 (on `.travis.yml`) or update it to the latest stable node.

Should `not` cause any backwards compatibility issues for users installing this through npm.

**Comment by stefnotch** [comment]
@andrevenancio I suppose the safest way is to upgrade it to something like node 5. 
Then, if nobody opens an issue, we can upgrade it to the latest node version.

**Comment by andrevenancio** [comment]
some other modules like `webpack-cli` (part of latest webpack) require `6.11.5` 💃 
What if we go with node 7? its 1 major version behind the current stable one. @stefnotch

**Comment by stefnotch** [comment]
@andrevenancio I guess that's fine.

So, can I merge this amazing PR?

**Comment by andrevenancio** [comment]
yeah I think so, all tests passed, version bump on the package.json, docs generated all should be good.

**Comment by stefnotch** [comment]
Awesome! Thank you! 👍

**Comment by stefnotch** [comment]
Yes, I'll do it. 😃

**Comment by TimvanScherpenzeel** [comment]
It is awesome that this library is getting updates again @stefnotch 👍

@andrevenancio thanks! It is great to see that this ticket has been merged.

**Pull request merged**
