### PR TITLE
Fixed an issue related to getRotation in mat4

### PR DESCRIPTION
**Pull request by alinz**
Fixed an issue as bitwise `&` was used instead of logical `&&`

### CODE REVIEW

**Comment by stefnotch** [comment]
@toji Are you still maintaining glmatrix?

**Comment by toji** [comment]
I would like to, but as a practical matter work and family have push upkeep of this library far down the priority stack for me. I apologize for the lack of attention to this repo, but I'm not sure when I'll be able to give it more of my time in the near term.

If someone else is interesting in helping maintain the project I'm open to it.

**Comment by stefnotch** [comment]
@toji Oh, I see. That's perfectly understandable. 

I would definitely be willing to maintain this repository.

**Comment by toji** [comment]
(Heh, while I'm here might as well merge this obviously good PR.)

Okay, I'll add you as an admin @stefnotch. Congrats. 😁 I don't think there's a ton to do, but having someone who's willing to vet pull requests and update the releases now and then would definitely be appreciated. Feel free to reach out to me directly if you have questions.

**Comment by stefnotch** [comment]
@toji Thanks! :)

So, my job is to 
- look at PRs, make sure that they are good (and have unit tests) and merge them
- address and close issues
- build everything and release updates
- keep the documentation up to date
- doing other stuff to keep the repository in a good shape
- anything else?

And, before doing anything major, I probably should ping or dm you?

**Pull request merged**
