### PR TITLE
In normalizing dual quaternions it is not sufficient just to divide a…

### PR DESCRIPTION
**Pull request by ptrebisz**
In normalizing dual quaternions it is not sufficient just to divide all elements by the magnitude of the real quaternion "A" which represents the rotation part. One also has to ensure that the second non-real quaternion "B" is perpendicular to "A". This is equivalent to dividing the dual quaternion by its dual norm. I fixed this bug.

### CODE REVIEW

**Comment by stefnotch** [comment]
Reference please? glm also simply divides all elements by the magnitude of the real quaternion : https://github.com/g-truc/glm/blob/398e66ac32f327539dc911b13095333266d0c5de/glm/gtx/dual_quaternion.inl#L230

**Comment by ptrebisz** [comment]
One good source for example is this paper about rigid body motion interpolation with dual quaternions

https://www.cs.utah.edu/~ladislav/kavan06dual/kavan06dual.pdf

On page 3 in section 3 there is a good description oft he norm of dual quaternions. The norm of a dual quaternion is not a single real number but a dual number, therefore dividing a dual quaternion by its norm is not as simple as with ordinary quaternions. The norm of a dual quaternion

A + epsilon*B

is

magnitude(A) + epsilon*dot(A, B)/magnitude(A)

To find the correct normalization formula you can write down this dual norm as a dual quaternion, take ist inverse and multiply it with the dual quaternion. Try this

(0, 0, 0, magnitude(A), 0, 0, 0, dot(A, B)/magnitude(A))^(-1) * (A, B)

Best regards
Piotr Trebisz



Von: stefnotch <notifications@github.com>
Gesendet: Dienstag, 10. Juli 2018 17:32
An: toji/gl-matrix <gl-matrix@noreply.github.com>
Cc: Trebisz, Piotr <piotr.trebisz@igd.fraunhofer.de>; Author <author@noreply.github.com>
Betreff: Re: [toji/gl-matrix] In normalizing dual quaternions it is not sufficient just to divide a… (#327)


Reference please? glm also simply divides all elements by the magnitude of the real quaternion : https://github.com/g-truc/glm/blob/398e66ac32f327539dc911b13095333266d0c5de/glm/gtx/dual_quaternion.inl#L230

**Comment by stefnotch** [comment]
So, this paper is wrong then: http://wscg.zcu.cz/wscg2012/short/A29-full.pdf

And [Magnum](http://magnum.graphics/) is also doing it wrong: https://github.com/mosra/magnum/blob/cc51bff893e52959060abf546c4ae86723d6abb6/src/Magnum/Math/DualQuaternion.h#L361

**Comment by ptrebisz** [comment]
Well it’s not generaly wrong. Usually if you create a dual quaternion from a rotation or translation or a combination of both then both components A and B will be perpendicular to each other and then you can skip the orthogonalization. But if you add 2 dual quaternions, for example during linear interpolation, then the result will not necessarily satisfy this orthogonal constraint anymore. Or if you multiply dual quaternions then rounding errors will also destroy this constraint.
A dual quaternion does represent a rigid body motion only when its norm is 1. As I mentioned before the general formula for the norm is

magnitude(A) + epsilon*dot(A, B)/magnitude(A)

So a dual quaternion does represent a rigid body motion if A has magnitude 1 and if A & B are orthogonal to each other, these 2 constraints have to be fulfilled.

Best regards
Piotr

Von: stefnotch <notifications@github.com>
Gesendet: Dienstag, 10. Juli 2018 18:34
An: toji/gl-matrix <gl-matrix@noreply.github.com>
Cc: Trebisz, Piotr <piotr.trebisz@igd.fraunhofer.de>; Author <author@noreply.github.com>
Betreff: Re: [toji/gl-matrix] In normalizing dual quaternions it is not sufficient just to divide a… (#327)


So, this paper is wrong then: http://wscg.zcu.cz/wscg2012/short/A29-full.pdf

And Magnum<http://magnum.graphics/> is also doing it wrong: https://github.com/mosra/magnum/blob/cc51bff893e52959060abf546c4ae86723d6abb6/src/Magnum/Math/DualQuaternion.h#L361

**Comment by ptrebisz** [comment]
I just looked into the paper to which you have sent the link. Take a look into section 7.1 (Dual Quaternion Arithmetic Operations). There you see the „Unit Condition“ with the two constraints which have to be satisfied ;-)

Piotr

Von: stefnotch <notifications@github.com>
Gesendet: Dienstag, 10. Juli 2018 18:34
An: toji/gl-matrix <gl-matrix@noreply.github.com>
Cc: Trebisz, Piotr <piotr.trebisz@igd.fraunhofer.de>; Author <author@noreply.github.com>
Betreff: Re: [toji/gl-matrix] In normalizing dual quaternions it is not sufficient just to divide a… (#327)


So, this paper is wrong then: http://wscg.zcu.cz/wscg2012/short/A29-full.pdf

And Magnum<http://magnum.graphics/> is also doing it wrong: https://github.com/mosra/magnum/blob/cc51bff893e52959060abf546c4ae86723d6abb6/src/Magnum/Math/DualQuaternion.h#L361

**Comment by stefnotch** [comment]
So, according to you, the example code in the paper is wrong? 

I've checked a few other libraries, and some of them agree with you.

**Comment by ptrebisz** [comment]
Hallo,
Sehe ich das richtig dass Du aus Österreich bist? Auf Deutsch kann ich etwas besser über Mathe diskutieren. Ich habe für ein besseres Verständnis ein Beispiel konstruiert wo die Normierung, so wie sie jetzt in der Lib ist, nicht funktionieren wird.

Nehmen wir an wir wollen zwischen zwei dualen Quaternionen D1 und D2 linear interpolieren. Das hier sind unsere beiden dualen Quaternionen:

D1 = [A1, B1] mit A1 = [0, 0, sqrt(1 / 2), sqrt(1 / 2)] & B1 = [0, 1, 0, 0]

D2 = [A2, B2] mit A2 = [0, sqrt(1 / 2), 0, sqrt(1 / 2)] & B2 = [0, 0, 1, 0]

Beides sind duale Quaternionen die die Einheitsbedingung erfüllen, denn es gilt

abs(A1) = 1 und dot(A1, B1) = 0 sowie abs(A2) = 1 und dot(A2, B2) = 0

So jetzt wollen wir zwischen den beiden interpolieren mit dem Interpolationsfaktor t = 0.5, dazu rechnen wir zuerst

D3 = [A3, B3] = (0.5 * D1) + (0.5 * D2)

Was kommt raus? Das kommt raus

A3 = [0, 0.5 * sqrt(1 / 2), 0.5 * sqrt(1 / 2), sqrt(1 / 2)] und B3 = [0, 0.5, 0.5, 0]

Jetzt normalisieren wir so wie es derzeit in der glMatrix Lib implementiert ist indem wir A3 und B3 durch abs(A3) teilen wobei abs(A3) = 0.5 * sqrt(3) ist. Und das kommt raus

A3 / abs(A3) = [0, sqrt(1 / 6), sqrt(1 / 6), 2 * sqrt(1 / 6)] und
B3 / abs(A3) = [0, sqrt(1 / 3), sqrt(1 / 3), 0]

Wie Du unschwer erkennen kannst verletzt das interpolierte duale Quaternion nach dieser Normalisierung die Bedingung das dot(A3, B3) = 0 sein muss. Das Ergebnis stellt keine starre Körper Transformation mehr da.

**Comment by stefnotch** [comment]
Ja, ich bin aus Österreich. 😄 

Also, ich habe mir das ein bisschen genauer angeschaut und wie es aussieht ist der jetzige Algorithmus zwar nicht ganz richtig, aber die Ergebnisse sind gut genug. Ich habe bis jetzt keinen Fall gefunden wo das nicht der Fall ist.
Ich habe https://github.com/chinedufn/skeletal-animation-system abgeändert so dass es den korrekten Algorithmus verwendet und `a_dot_b` ausgegeben. (Wenn `a_dot_b` fast 0 ist, sind die Ergebnisse der beiden Algorithmen fast identisch.)
```
...
0.0018417507246217824 bundle.js:5695:32
-0.002262178453594957 bundle.js:5695:32
-0.0015822409867984888 bundle.js:5695:32
0.001619196635042619 bundle.js:5695:32
-0.0019910373337700543 bundle.js:5695:32
-0.0010972887446664137 bundle.js:5695:32
0.001121796382368645 bundle.js:5695:32
-0.0013828500440117159 bundle.js:5695:32
-0.0011059833193633184 bundle.js:5695:32
-0.0016297593155614187 bundle.js:5695:32
-0.002134986289319185 bundle.js:5695:32
-0.0021348732813510907 bundle.js:5695:32
-0.0027379122229591046 bundle.js:5695:32
-0.002310119667470134 bundle.js:5695:32
-0.003032050493105176 bundle.js:5695:32
-0.003031889912032848 bundle.js:5695:32
0.001347546357114121 bundle.js:5695:32
0.001347571858389851 bundle.js:5695:32
0.0011719656134439038 bundle.js:5695:32
-0.0038985829029382635 bundle.js:5695:32
0.0012523894528164783 bundle.js:5695:32
0.0013011066211784383 bundle.js:5695:32
-0.002788158339550706 bundle.js:5695:32
-0.0036644183858134394 bundle.js:5695:32
-0.0036642241995971103 bundle.js:5695:32
0.0016261151176278354 bundle.js:5695:32
0.0016261458624794445 bundle.js:5695:32
0.001414443338685456 bundle.js:5695:32
-0.00472052130042841 bundle.js:5695:32
0.0015117790432761236 bundle.js:5695:32
0.0015784034955728665 bundle.js:5695:32
-0.0030135719805771954 bundle.js:5695:32
-0.003963200142459655 bundle.js:5695:32
-0.003962990002044808 bundle.js:5695:32
0.0017574374435917473 bundle.js:5695:32
0.0017574706409435592 bundle.js:5695:32
0.0015287761636085806 bundle.js:5695:32
-0.005109962850993216 bundle.js:5695:32
0.001634118617440613 bundle.js:5695:32
0.0017101662907294535 bundle.js:5695:32
...
```

Danach habe ich es mit deinem Beispiel ausprobiert.
```javascript

var xx = quat2.fromValues(0, Math.sqrt(1 / 6), Math.sqrt(1 / 6), 2 * Math.sqrt(1 / 6), 0, Math.sqrt(1 / 3), Math.sqrt(1 / 3), 0);
//> Float32Array(8) [ 0, 0.40824830532073975, 0.40824830532073975, 0.8164966106414795, 0, 0.5773502588272095, 0.5773502588272095, 0 ]

// Ja, da ist ein definitiv ein Unterschied
normalizeQ(quat2.create(), xx)
// a_dot_b: 0.47140451233015424
//> Float32Array(8) [ 0, 0.40824830532073975, 0.40824830532073975, 0.8164966106414795, 0, 0.38490015268325806, 0.38490015268325806, -0.38490015268325806 ]

// Also, der Teil der die Position repräsentiert ist anders. Schauen wir uns doch mal die beiden an. 
quat2.getTranslation(vec3.create(), xx)
//> Float32Array(3) [ 0, 0.9428090453147888, 0.9428090453147888 ]
quat2.getTranslation(vec3.create(), normalizeQ(quat2.create(), xx))
//> Float32Array(3) [ 0, 0.942808985710144, 0.942808985710144 ]

// Wie es aussieht ist der Unterschied doch nicht so groß
```

`keine starre Körper Transformation mehr da.`
Also kann eine duale Quaternion mehr als nur eine Position und eine Rotation sein. Interessant...


### And here is the English translation for future readers:

After investigating a bit, it appears that in the vast majority, if not all cases, the current algorithm yields good enough results. 
I modified https://github.com/chinedufn/skeletal-animation-system to use the correct normalization algorithm and constantly printed the value of `a_dot_b` (If `a_dot_b` is close to 0, the 2 normalization algorithms return almost identical results)
```
...
0.0018417507246217824 bundle.js:5695:32
-0.002262178453594957 bundle.js:5695:32
-0.0015822409867984888 bundle.js:5695:32
0.001619196635042619 bundle.js:5695:32
-0.0019910373337700543 bundle.js:5695:32
-0.0010972887446664137 bundle.js:5695:32
0.001121796382368645 bundle.js:5695:32
-0.0013828500440117159 bundle.js:5695:32
-0.0011059833193633184 bundle.js:5695:32
-0.0016297593155614187 bundle.js:5695:32
-0.002134986289319185 bundle.js:5695:32
-0.0021348732813510907 bundle.js:5695:32
-0.0027379122229591046 bundle.js:5695:32
-0.002310119667470134 bundle.js:5695:32
-0.003032050493105176 bundle.js:5695:32
-0.003031889912032848 bundle.js:5695:32
0.001347546357114121 bundle.js:5695:32
0.001347571858389851 bundle.js:5695:32
0.0011719656134439038 bundle.js:5695:32
-0.0038985829029382635 bundle.js:5695:32
0.0012523894528164783 bundle.js:5695:32
0.0013011066211784383 bundle.js:5695:32
-0.002788158339550706 bundle.js:5695:32
-0.0036644183858134394 bundle.js:5695:32
-0.0036642241995971103 bundle.js:5695:32
0.0016261151176278354 bundle.js:5695:32
0.0016261458624794445 bundle.js:5695:32
0.001414443338685456 bundle.js:5695:32
-0.00472052130042841 bundle.js:5695:32
0.0015117790432761236 bundle.js:5695:32
0.0015784034955728665 bundle.js:5695:32
-0.0030135719805771954 bundle.js:5695:32
-0.003963200142459655 bundle.js:5695:32
-0.003962990002044808 bundle.js:5695:32
0.0017574374435917473 bundle.js:5695:32
0.0017574706409435592 bundle.js:5695:32
0.0015287761636085806 bundle.js:5695:32
-0.005109962850993216 bundle.js:5695:32
0.001634118617440613 bundle.js:5695:32
0.0017101662907294535 bundle.js:5695:32
...
```

After that, I tried it out with your example values:
```javascript

// Creating a dual quaternion
var xx = quat2.fromValues(0, Math.sqrt(1 / 6), Math.sqrt(1 / 6), 2 * Math.sqrt(1 / 6), 0, Math.sqrt(1 / 3), Math.sqrt(1 / 3), 0);
//> Float32Array(8) [ 0, 0.40824830532073975, 0.40824830532073975, 0.8164966106414795, 0, 0.5773502588272095, 0.5773502588272095, 0 ]

// The normalized dual quaternion clearly is different from the non-normalized one
normalizeQ(quat2.create(), xx)
// a_dot_b: 0.47140451233015424
//> Float32Array(8) [ 0, 0.40824830532073975, 0.40824830532073975, 0.8164966106414795, 0, 0.38490015268325806, 0.38490015268325806, -0.38490015268325806 ]

// So, let's get the different parts  (the translation part)
quat2.getTranslation(vec3.create(), xx)
//> Float32Array(3) [ 0, 0.9428090453147888, 0.9428090453147888 ]
quat2.getTranslation(vec3.create(), normalizeQ(quat2.create(), xx))
//> Float32Array(3) [ 0, 0.942808985710144, 0.942808985710144 ]

// Turns out that they are almost identical...
```

`keine starre Körper Transformation mehr da.`
So, you can encode more than just a rotation and a translation in a dual quaternion? That's interesting.

**Comment by stefnotch** [comment]
Since when using your example, the properly normalized quaternion is quite different from the not-properly normalized quaternion, I'm definitely going to have to take a closer look at this issue.

**Pull request merged**
