### PR TITLE
Adding outer product to matrix modules.

### PR DESCRIPTION
**Pull request by ptpham**

### CODE REVIEW

**Comment by stefnotch** [comment]
My mathematics background isn't too strong, so, would you mind explaining what an outer product is? And, more importantly, when do you need it?

**Comment by ptpham** [comment]
Note that the outer product I'm referring to is an algebraic reformulation of the product of P transpose and Q. Instead of doing that matrix multiplication, it is equivalent to do a sum of outer products of the rows of P and Q.

**Comment by stefnotch** [comment]
@ptpham That's interesting. :) However, I'm not sure how many people need this feature.

What do you think about creating an issue where all sorts of features can be requested and voted on? And, if enough people are interested in something, it may get added to the library.

**Comment by ptpham** [comment]
Haha. Well, it's okay. I made a fork a while ago anyways to better suit my use cases. XD Thanks for the interest. =P

**Pull request closed without merging**
