### PR TITLE
SIMD implementation of mat4.{scale, translate, transpose, adjoint, invert}

### PR DESCRIPTION
**Pull request by sajjadt**
Added SIMD implementation of mat4.{scale, translate, transpose, adjoint, invert} operations.

### CODE REVIEW

**Comment by toji** [comment]
This is looking great! The only thing missing is tests, as mentioned in the previous patch. All you should need to do for that is to go into spec/gl-matrix/mat4-spec.js and change the calls for these functions from `mat4.scale` to `mat4.TEST_PATH.scale`, etc. That will make sure the tests exercise both paths.

**Comment by sajjadt** [comment]
Thanks for the review! Tests now are updated to cover SIMD versions as well.

**Comment by toji** [comment]
Perfect! Thanks for the contribution!

**Comment by nickdesaulniers** [comment]
:beers: :rocket: :snowboarder:

**Pull request merged**
