### PR TITLE
mat4.fromRotationTranslationScaleOrigin slight speedup

### PR DESCRIPTION
**Pull request by flowtsohg**
Cached local array accesses.

I doubt many people will notice the difference.
My library calls this function possibly millions of times per second, so every bit of speed counts.

### CODE REVIEW

**Comment by toji** [comment]
This change needs to be rebased against master now that #249 has landed, but I'd be happy to merge it at that point, thanks!

**Comment by stefnotch** [comment]
@flowtsohg Mind updating your pull request?

**Comment by flowtsohg** [comment]
I am not very experienced with Github, does this mean I need to re-fork the repository and re-pull?

**Comment by stefnotch** [comment]
@flowtsohg You don't need a new fork. You have to **pull** from the latest master, fix the merge conflicts and then, you would have to **commit** and **push**.

Though, it should be easily possible to resolve the merge conflicts right here in the browser: https://help.github.com/articles/resolving-a-merge-conflict-on-github/

**Comment by flowtsohg** [comment]
I am pretty sure I messed something up, but I guess it worked in the end. :)

**Comment by stefnotch** [comment]
@toji This change can now be merged.

**Comment by stefnotch** [comment]
@toji Mind merging this?

**Pull request merged**
