### PR TITLE
targetTo implementation

### PR DESCRIPTION
**Pull request by stefnotch**
https://github.com/toji/gl-matrix/issues/225

### CODE REVIEW

**Comment by toji** [comment]
Okay, apologies for throwing a wrench into things but I've just merged #249 which definitely conflicts with this PR. I appreciate the work that's gone into it, though, and would like to merge this functionality before we officially mark the 2.4.0 release. I'm happy to do the conversion, it's not terribly difficult, but if you would like to do the conversion yourself then it's easier for GitHub to give "credit" to the appropriate developer.

Thanks for the contribution, and for the considerate discussion leading up to it!

**Comment by stefnotch** [comment]
@toji Oh, great to see you being active here again. :D I am going to do the conversions myself, it shouldn't take too long.

**Comment by stefnotch** [comment]
Ok, I manged to fix the merge conflicts. 

By the way, I cannot guarantee that my code is correct.

**Comment by toji** [comment]
Your docs changes have merge conflict markers in them. You could probably just delete the docs directory and run `npm run docs` again to get a clean build.

The bit with Travis saying there's 1 pending test is a pre-existing condition that I need to dig into, unrelated to this change.

**Comment by stefnotch** [comment]
Oh, my bad. Well, it should be fixed now.

**Comment by stefnotch** [comment]
A lot of stuff regarding the docs has changed. (Most file names are different.)

**Comment by toji** [comment]
You're right, I hadn't rebuilt the docs recently so it was a bit of a mess. Sorry!

I did a bit of command line jiggery-pokery and stripped the docs changes out of your PR, landed just your code and test changes, and then regenerated the docs myself as a separate commit. This seems to have [gone through pretty cleanly](https://github.com/toji/gl-matrix/commit/bdad48e89ec2341d8b0be3c9bd82c10532fda27c) and still preserved you as the author of the `targetTo` change. (Hooray!)

So I'm closing this issue and I think GitHub will consider it to be unmerged, but rest assured that your change did make it in.

**Comment by stefnotch** [comment]
That's great! :D

**Comment by andrevenancio** [comment]
When pulled as npm module this doesnt come through. my mat4 doesnt have the 'targetTo' method

**Comment by toji** [comment]
What version did you receive when you pulled the NPM module? Should be 2.4.0. I just pulled it myself and it synced the latest version which I confirmed had the `targetTo` function. (In both the src/ and dist/ files.)

**Comment by andrevenancio** [comment]
You're right! I had a fight with my version system. running `yarn` updated the yarn.lock and also `rm -rf node_modules && npm i` should update package-lock.json for those of you using npm all good!

**Comment by andrevenancio** [comment]
Oh actually, I think you added the `src` folder as the entry point. shouldnt we have a compiled output to es6 instead?

**Comment by toji** [comment]
The [package file](https://github.com/toji/gl-matrix/blob/master/package.json) points to `dist/gl-matrix.js` as the "main" target, which is a compiled version that strips out any modules requirement. I did add a "modules" target of `src/gl-matrix.js`, but your code shouldn't ever use that unless you're actively using modules yourself, in which case that's probably the version you want anyway.

**Comment by andrevenancio** [comment]
Hey, yeah it works. There's still no "right way of doing it" But some major projects like React-Redux are exporting an ES6 version to the module end point. Its fine, this way too :) I just had to fix my project's webpack config since I've updated gl-matrix to this version. All good :)

**Pull request closed without merging**
