### PR TITLE
Replace webpack with rollup

### PR DESCRIPTION
**Pull request by TrySound**
This reduced the size of minified umd bundle from 56kB to 52kB.
Configurations was combined into multiconfig to simplify maintainment.

Terser is prefered over uglify as more stable package.

### CODE REVIEW

**Comment by TrySound** [comment]
I think we are ready for release.

**Comment by stefnotch** [comment]
Looks good, I'll merge it after giving @andrevenancio some time to look at it.

**Comment by andrevenancio** [comment]
Looks pretty good to me. Should we just update the README.md with the different import options we now have?

I assume we still need to specify something along the lines of
```javascript
import { vec2 } from 'gl-matrix/ejs' ?
```

Or we dont @TrySound ?

**Comment by stefnotch** [comment]
Ok, I'm merging it then.

**Comment by stefnotch** [comment]
Just wanted to point out a minor observation:
When simply including dist/gl-matrix.js in your website and not importing it, you now have to include `glMatrix.` before everything (e.g. `glMatrix.vec4.create()` instead of `vec4.create()`)

That's definitely a breaking change.

**Comment by TrySound** [comment]
Hm.. I guess I skipped this part. But anyways polluting window is not good practice.

**Comment by stefnotch** [comment]
Yeah, I'm quite fine with it. I only noticed it when answering someone's question about gl-matrix, because when testing something, I usually just run it in the browser console.

**Comment by andrevenancio** [comment]
Yeah for es5 code I think adding to a glMatrix variable on the window makes sense and its quite a common practise. we avoid window pollution and I think most people are used to it. I suppose we might need to improve documentation with a basic example and I'm happy to pick up that myself at some point soon and do a PR. Looks great @TrySound thanks. Do you also have access to the glmatrix website @stefnotch? Is it worth adding a paragraph mentioning all the module options for more advanced users?

**Comment by TrySound** [comment]
@stefnotch Could you also publish this prerelease on npm? You may use `npm publish --tag=next` and the version like `3.0.0-0`

**Comment by stefnotch** [comment]
> Do you also have access to the glmatrix website @stefnotch? Is it worth adding a paragraph mentioning all the module options for more advanced users?

Yes, I do. (It's just GitHub pages)

**Comment by stefnotch** [comment]
@TrySound Regarding publishing it to npm:
```
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
```

Do I have to publish every single sub-package or...?

**Comment by TrySound** [comment]
I mentioned in https://github.com/toji/gl-matrix/pull/343
image

**Comment by stefnotch** [comment]
Oh, thank you. I'm sorry for not properly reading it the first time.

[I published it to `npm` now](https://www.npmjs.com/package/gl-matrix?activeTab=versions)

**Comment by TrySound** [comment]
Great! Thank you

**Pull request merged**
